In [ ]:
#HAP SAD SUR ANG DIS FEA PIC

In [2]:
%mkdir happy
%mkdir sad
%mkdir surprise
%mkdir angry
%mkdir disgust
%mkdir fear

A subdirectory or file happy already exists.
A subdirectory or file sad already exists.
A subdirectory or file surprise already exists.
A subdirectory or file angry already exists.
A subdirectory or file disgust already exists.
A subdirectory or file fear already exists.


In [3]:
import pandas

df = pandas.read_table('./jan.txt', delim_whitespace=True, names=('happy', 'sad', 'surprise','angry','disgust','fear','neutral','pic'))

In [4]:
df

happy   sad  surprise  angry  disgust  fear  neutral     pic
0        1  2.87      2.52   2.10     1.97  1.97     2.06  KM-NE1
1        2  2.87      2.42   1.58     1.84  1.77     1.77  KM-NE2
2        3  2.50      2.10   1.70     1.50  1.73     1.53  KM-NE3
3        4  4.90      1.13   1.26     1.10  1.03     1.10  KM-HA1
4        5  4.87      1.20   1.43     1.03  1.07     1.07  KM-HA2
..     ...   ...       ...    ...      ...   ...      ...     ...
214    215  1.45      3.19   1.81     3.16  4.19     2.77  NA-DI2
215    216  1.43      2.87   1.77     4.33  3.87     2.10  NA-DI3
216    217  1.61      2.68   4.10     3.16  3.81     3.90  NA-FE1
217    218  1.68      3.10   3.74     3.19  3.58     3.87  NA-FE2
218    219  1.48      3.26   3.39     2.71  3.06     3.74  NA-FE3

[219 rows x 8 columns]

In [44]:
df1 = np.array(df.iloc[:,1:-2])
print(df1)
cls = df1.argmax(axis=1)
print(cls)

[[2.87 2.52 2.1  1.97 1.97 2.06]
 [2.87 2.42 1.58 1.84 1.77 1.77]
 [2.5  2.1  1.7  1.5  1.73 1.53]
 ...
 [1.61 2.68 4.1  3.16 3.81 3.9 ]
 [1.68 3.1  3.74 3.19 3.58 3.87]
 [1.48 3.26 3.39 2.71 3.06 3.74]]
[0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 3 3 3 4 4 4 4 5 4 0 0 0 0 0 0 0 1 1 1 2 2
 2 3 3 4 4 4 4 5 4 2 2 1 0 0 0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 1 5 1 2 3 3 3 0
 0 0 1 1 1 2 2 2 3 3 3 4 4 3 2 2 2 0 0 0 0 0 0 1 1 1 2 2 2 0 3 4 4 0 4 5 2
 2 0 0 0 0 0 0 1 1 1 2 2 2 3 4 4 4 4 4 5 2 5 0 1 1 0 0 0 1 1 1 2 2 2 3 3 3
 4 4 4 1 1 1 2 1 2 0 0 0 1 1 1 2 2 2 3 3 4 4 4 4 4 4 4 4 0 0 0 0 0 0 0 1 1
 1 2 2 2 3 3 3 4 4 4 4 4 4 0 0 0 0 0 0 1 1 3 0 2 2 3 3 3 4 4 3 2 5 5]


In [52]:
cls1 = pd.DataFrame(cls)
df['pic']

0      KM-NE1
1      KM-NE2
2      KM-NE3
3      KM-HA1
4      KM-HA2
        ...  
214    NA-DI2
215    NA-DI3
216    NA-FE1
217    NA-FE2
218    NA-FE3
Name: pic, Length: 219, dtype: object

In [65]:
df_concat = pd.concat([df['pic'], cls1], axis=1)
df_concat.columns=['pic','class']
df_concat

pic  class
0    KM-NE1      0
1    KM-NE2      0
2    KM-NE3      0
3    KM-HA1      0
4    KM-HA2      0
..      ...    ...
214  NA-DI2      4
215  NA-DI3      3
216  NA-FE1      2
217  NA-FE2      5
218  NA-FE3      5

[219 rows x 2 columns]

In [68]:
len(df_concat)
df_concat.iloc[3]['class']

0

In [70]:
%pwd

'C:\\Users\\rn0610\\Desktop\\P_folder\\P_W251\\finalProject\\jaffedbase\\jaffedbase'

In [76]:
import os
img_list_tiff=[]
img_list = os.listdir('C:\\Users\\rn0610\\Desktop\\P_folder\\P_W251\\finalProject\\jaffedbase\\jaffedbase')
for i in img_list:
    if i.endswith('tiff'):
        img_list_tiff.append(i)
img_list_tiff
    

['KA.AN1.39.tiff',
 'KA.AN2.40.tiff',
 'KA.AN3.41.tiff',
 'KA.DI1.42.tiff',
 'KA.DI2.43.tiff',
 'KA.DI3.44.tiff',
 'KA.FE1.45.tiff',
 'KA.FE2.46.tiff',
 'KA.FE3.47.tiff',
 'KA.FE4.48.tiff',
 'KA.HA1.29.tiff',
 'KA.HA2.30.tiff',
 'KA.HA3.31.tiff',
 'KA.HA4.32.tiff',
 'KA.NE1.26.tiff',
 'KA.NE2.27.tiff',
 'KA.NE3.28.tiff',
 'KA.SA1.33.tiff',
 'KA.SA2.34.tiff',
 'KA.SA3.35.tiff',
 'KA.SU1.36.tiff',
 'KA.SU2.37.tiff',
 'KA.SU3.38.tiff',
 'KL.AN1.167.tiff',
 'KL.AN2.168.tiff',
 'KL.AN3.169.tiff',
 'KL.DI1.170.tiff',
 'KL.DI2.171.tiff',
 'KL.DI3.172.tiff',
 'KL.DI4.173.tiff',
 'KL.FE1.174.tiff',
 'KL.FE2.175.tiff',
 'KL.FE3.176.tiff',
 'KL.HA1.158.tiff',
 'KL.HA2.159.tiff',
 'KL.HA3.160.tiff',
 'KL.NE1.155.tiff',
 'KL.NE2.156.tiff',
 'KL.NE3.157.tiff',
 'KL.SA1.161.tiff',
 'KL.SA2.162.tiff',
 'KL.SA3.163.tiff',
 'KL.SU1.164.tiff',
 'KL.SU2.165.tiff',
 'KL.SU3.166.tiff',
 'KM.AN1.17.tiff',
 'KM.AN2.18.tiff',
 'KM.AN3.19.tiff',
 'KM.DI1.20.tiff',
 'KM.DI3.22.tiff',
 'KM.FE1.23.tiff',
 'KM.FE2.

In [127]:
df_concat.iloc[0]['pic']

'KM-NE1'

In [131]:
name=[]
for i in range(len(df_concat)):
    for j in range(len(img_list_tiff)):
        if df_concat.iloc[i]['pic'] == img_list_tiff[j][:6].replace('.','-'):
            name.append(img_list_tiff[j])
name1 = pd.DataFrame(name)
len(name1)

212

In [132]:
df2 = pd.concat([df_concat, name1], axis=1)
df2.to_csv('jandata.csv')

In [148]:
df3 = pd.read_csv('jandata.csv')
df3.columns=['num','pic','class','fullname0','fullname']
df4 = df3.drop(['num','fullname0'],axis=1)
df4

pic  class         fullname
0    KM-NE1      0    KM.NE1.1.tiff
1    KM-NE2      0    KM.NE2.2.tiff
2    KM-NE3      0    KM.NE3.3.tiff
3    KM-HA1      0    KM.HA1.4.tiff
4    KM-HA2      0    KM.HA2.5.tiff
..      ...    ...              ...
207  NA-DI2      4  NA.DI2.215.tiff
208  NA-DI3      3  NA.DI3.216.tiff
209  NA-FE1      2  NA.FE1.217.tiff
210  NA-FE2      5  NA.FE2.218.tiff
211  NA-FE3      5  NA.FE3.219.tiff

[212 rows x 3 columns]

In [ ]:
import shutil, os
files = ['file1.txt', 'file2.txt', 'file3.txt']
for f in files:
    shutil.move(f, 'dest_folder')

In [152]:
# 0: happy, 1:sad, 2:surprise, 3:angry, 4:disgust, 5:fear
import shutil, os
for i in range(len(df4)):
    image_name = df4.iloc[i]['fullname']
    image_class = df4.iloc[i]['class']
    path='C:\\Users\\rn0610\\Desktop\\P_folder\\P_W251\\finalProject\\jaffedbase\\jaffedbase\\'
    if image_class == 0:
        shutil.move(path+image_name,'C:\\Users\\rn0610\\Desktop\\P_folder\\P_W251\\finalProject\\jaffedbase\\jaffedbase\\happy')
    elif image_class == 1:
        shutil.move(path+image_name,'C:\\Users\\rn0610\\Desktop\\P_folder\\P_W251\\finalProject\\jaffedbase\\jaffedbase\\sad')
    elif image_class == 2:
        shutil.move(path+image_name,'C:\\Users\\rn0610\\Desktop\\P_folder\\P_W251\\finalProject\\jaffedbase\\jaffedbase\\surprise')
    elif image_class == 3:
        shutil.move(path+image_name,'C:\\Users\\rn0610\\Desktop\\P_folder\\P_W251\\finalProject\\jaffedbase\\jaffedbase\\angry')
    elif image_class == 4:
        shutil.move(path+image_name,'C:\\Users\\rn0610\\Desktop\\P_folder\\P_W251\\finalProject\\jaffedbase\\jaffedbase\\disgust')
    else:
        shutil.move(path+image_name,'C:\\Users\\rn0610\\Desktop\\P_folder\\P_W251\\finalProject\\jaffedbase\\jaffedbase\\fear')

In [157]:
def jpeg_res(filename):
    with open(filename,'rb') as img_file:
        #height of image (in 2 bytes) is at 164th position
        img_file.seek(163)

        # read the 2 bytes
        a = img_file.read(2)

        # calculate height
        height = (a[0] << 8) + a[1]

        # next 2 bytes is width
        a = img_file.read(2)

        # calculate width
        width = (a[0] << 8) + a[1]

        print("The resolution of the image is",width,"x",height)

jpeg_res(path + "happy\\KA.HA2.30.tiff")

The resolution of the image is 46005 x 46517
